/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include"stm32f411xe.h"
#include "led.h"
#include "usart.h"

int main(void)
{
    /* Loop forever */
    PortD_EnableBus();
    PortA_EnableBus();
    Usart2_Enable_Bus_Pin();
    Usart2_Init();
	while(1)
  {
    uint8_t button = (GPIOA->IDR) & 0x01;
     if(button != 0)
     {
      Led_Control(LED_ON);
     }
     else
     {
      Led_Control(LED_OFF);
     }
  }
}
